REACT_APP_BASEURL = ${REACT_APP_BASEURL}
REACT_APP_BASEURL_without_slash = ${REACT_APP_BASEURL_without_slash}
REACT_APP_BASEURL_without_slash_view_data = ${REACT_APP_BASEURL_without_slash_view_data}
DATAHUB_NAME: ${DATAHUB_NAME}
DATAHUB_SITE: ${DATAHUB_SITE}
POSTGRES_DB: ${POSTGRES_DB}
POSTGRES_USER: ${POSTGRES_USER}
POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD}
SENDGRID_API_KEY: ${SENDGRID_API_KEY}
EMAIL_HOST_USER: ${EMAIL_HOST_USER}
PORT: ${PORT}
