version: '3'

services:

  steward-ui:
    image: farmstack/steward-ui:${FS_STEWARD_UI_VERSION}
    container_name: fs-steward-ui
    env_file:
      - ./.env
    volumes:
      - ./config/env_frontend.sh:/docker-entrypoint.d/env.sh
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx-cert/public.crt:/etc/nginx/cert/public.crt
      - ./nginx-cert/private.key:/etc/nginx/cert/private.key
    ports:
      - "443:443"
      - "80:80"
    networks:
      - mysql-network

networks:
  mysql-network:
    driver: bridge
