version: '3'

services:

  steward-ui:
    image: farmstack/steward-ui:test
    container_name: fs-steward-ui
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public.crt:/etc/nginx/cert/public.crt
      - ./private.key:/etc/nginx/cert/private.key
    ports:
      - "443:443"
      - "80:80"
    networks:
      - mysql-network

networks:
  mysql-network:
    driver: bridge
